---

- name: pull {{ srsran.docker.container.gnb_image }} image
  community.docker.docker_image:
    name: "{{ srsran.docker.container.gnb_image }}"
    source: pull
  when: inventory_hostname in groups['srsran_nodes']
  become: true

- name: remove /tmp/gnb_config.yaml
  file:
    path: "/tmp/gnb_config.yaml"
    state: absent
  when: inventory_hostname in groups['srsran_nodes']
  become: true

- name : copy gnb config file to /tmp/gnb_config.yaml
  template:
    src: "{{ ROOT_DIR }}/{{ srsran.gnb.conf_file }}"
    dest: /tmp/gnb_config.yaml
  when: inventory_hostname in groups['srsran_nodes']
  become: true

- name: create {{ srsran.docker.container.gnb_image }} containers
  community.docker.docker_container:
    name: "srsran-gnb"
    image: "{{ srsran.docker.container.gnb_image }}"
    networks:
      - name: "{{ srsran.docker.network.name }}"
    volumes:
      - /tmp/gnb_config.yaml:/opt/gnb_config.yaml
    privileged: true
    state: started
    detach: true
    command: "gnb -c /opt/gnb_config.yaml"
  when: inventory_hostname in groups['srsran_nodes']
  become: true
