---

- name: delete {{ srsran.docker.container.gnb_image }} container
  community.docker.docker_container:
    name: "srsran-gnb"
    state: absent
  when: inventory_hostname in groups['srsran_nodes']
  become: true

- name: remove /tmp/gnb_config.yaml
  file:
    path: "/tmp/gnb_config.yaml"
    state: absent
  when: inventory_hostname in groups['srsran_nodes']
  become: true
