---

- name: check if servers and config server length are equal
  fail:
    msg: "Mismatch in number of servers and srsran nodes: {{ srsran.servers|length }} vs {{ groups['srsran_nodes']|length }}"
  when: srsran.servers|length != groups['srsran_nodes']|length

- name: delete {{ srsran.docker.container.ue_image }} container
  community.docker.docker_container:
    name: "rfsim5g-srsran-nr-ue"
    state: absent
  when: inventory_hostname in groups['srsran_nodes']
  become: true

- name: remove /tmp/ue_zmq.conf
  file:
    path: "/tmp/ue_zmq.conf"
    state: absent
  when: inventory_hostname in groups['srsran_nodes']
  become: true

- name: remove {{ srsran.docker.container.ue_image }} image
  community.docker.docker_image:
    name: "{{ srsran.docker.container.ue_image }}"
    state: absent
    force_absent: true
  when: inventory_hostname in groups['srsran_nodes']
  become: true
